version: "3"
services:
  app:
    build: .
    ports:
      - 8050:8050
    command: yarn start
    volumes:
      - ./src:/app/src
    tty: true
  test:
    build: .
    command: yarn test
    volumes:
      - ./src:/app/src
    tty: true
